import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "@/components/Header";
import BoxMain from "@/components/BoxMain";
import { Grid, Typography } from "@mui/material";
import { motion } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Grid container sx={{ padding: 10, pt: 15 }} spacing={2}>
          <Grid item xs={12} sm={8} component={motion.div} whileHover="test">
            <BoxMain>
              <Grid
                component={motion.div}
                container
                justifyContent="center"
                direction="column"
                sx={{ height: "100%", position: "relative" }}
                variants={{
                  test: {
                    opacity: 0,
                    top: "100px",
                    transition: { duration: 0.2 },
                  },
                }}
              >
                <Typography variant="h4" fontWeight={600}>
                  Hi, My name is Ilemar
                </Typography>
                <Typography variant="body1">
                  &quot;Nada es imposible&quot;
                </Typography>
              </Grid>
              <Grid
                component={motion.div}
                sx={{ height: "100%", position: "absolute", padding: "25px" }}
                initial={{ top: "10%", opacity: 0 }}
                variants={{
                  test: {
                    opacity: 1,
                    top: "0px",
                    transition: { duration: 0.2 },
                  },
                }}
              >
                <Typography variant="h2" fontWeight={600}>
                  Learn <br /> more
                  <br /> about me
                </Typography>
              </Grid>
            </BoxMain>
          </Grid>
          <Grid item xs={12} sm={4}>
            <BoxMain />
          </Grid>
          <Grid item xs={12} sm={4}>
            <BoxMain />
          </Grid>
          <Grid item xs={12} sm={6}>
            <BoxMain />
          </Grid>
          <Grid item xs={12} sm={6}>
            <BoxMain />
          </Grid>
          <Grid item xs={12} sm={6}>
            <BoxMain />
          </Grid>
          <Grid item xs={12} sm={12}>
            <BoxMain />
          </Grid>
          <Grid item xs={12} sm={4}>
            <BoxMain />
          </Grid>
          <Grid item xs={12} sm={4}>
            <BoxMain />
          </Grid>
          <Grid item xs={12} sm={4}>
            <BoxMain />
          </Grid>
          <Grid item xs={12} sm={4}>
            <BoxMain />
          </Grid>
        </Grid>
      </main>
    </>
  );
}
